### ISSUE TITLE
Only part of North and South Pole displayed based on zoom level

### ISSUE THREAD

**Issue by esh0** [googlemaps/android-samples#1072]
#### Environment details

Google Maps SDK for Android

OS type and version

Android API 30, Pixel Emulator

#### Expected behavior

The top and bottom of world are visible no matter of zoom level.

#### Observed behavior

The more zoom level is, the less top and bottom parts of World are displayed.

#### Steps to reproduce

https://user-images.githubusercontent.com/5416378/193782864-55d61180-4970-4d7e-af0f-96ad511fd6db.mov

From android-samples/kotlin take any sample where zoom and scroll is allowed, i.e. UiSettingdDemoActivity
Change map's fragment height from "match_parent" to some smaller size, i.e. 250dp
Zoom out max the map and try to scroll to North Pole, until no more scroll is possible - only some part is displayed
Zoom in one step and try to scroll to North Pole, until no more scroll is possible - more top part of the World is visible
Zoom out one step - observe that map scrolls automatically and no more area from point above is displayed

Is this desired behavior or there are some settings missing for map to work the same way no matter what zoom level is?

**Comment by wangela** [comment]
If you change the fragment height after map creation, you may need to [update the map padding](https://developers.google.com/maps/documentation/android-sdk/configure-map#set_up_map_padding).

The flow you describe above is working as intended because the map was [added statically](https://github.com/googlemaps/android-samples/blob/main/ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/UiSettingsDemoActivity.kt#L42) (see discussion about [adding the map statically vs dynamically ](https://developers.google.com/maps/documentation/android-sdk/map#addfragment)) and then what you're suggesting is manipulating the fragment height after creation. It would be better to [add the map dynamically](https://developers.google.com/maps/documentation/android-sdk/map#to_add_a_fragment_dynamically) with the desired fragment height, then you can [configure the map](https://developers.google.com/maps/documentation/android-sdk/configure-map).

**Comment by esh0** [comment]
@wangela Thank you for answer, but I think I don't quite understand the behavior. Fragment is added statically in layout and there it's height is set (so height is set in XML, not after map creation). This means, that fragment knows it's height when is created. Are you sure your answer is taking this into consideration? If I understood correctly the documentation, then if it would be a problem with padding, then also zoom controls would be padded - but as you can see on the video, they are not. Would you mind checking the issue again?
