### ISSUE TITLE
Changing date on the device break the map

### ISSUE THREAD

**Issue by pawelrybicki** [googlemaps/android-samples#122]
Steps to reproduce:
1. Clear samples-app data on the device
2. Change device date to custom, let's say 2 months prior to today
3. Open samples-app and try to display the map

The map is no longer visible like it has not been initialized. I have found that while `getMapAsync` is being called, `setOnMapLoadedCallback` is not.

I have found this issue when playing with lite-maps. Keep in mind that if you will display some area correctly (with a current date on the device), and then change the date in the system, and try to display the area again, `setOnMapLoadedCallback` will be called and the map will be visible. It is probably due to caching etc. It is why it is important to clear app data before attempting to display the map after you change the date on the device.

**Comment by amuramoto** [comment]
This is likely in the SDK itself rather than the util lib. I don't know that I would classify it as a bug since this would only happen in a particular development instance, but please feel free to file a bug in the issue tracker for the SDK if you think it should be addressed:

https://issuetracker.google.com/savedsearches/5446940
