### ISSUE TITLE
Exposed API key in string resources and manifest

### ISSUE THREAD

**Issue by dave-kennedy** [googlemaps/android-samples#200]
I believe adding the API key to string resources in build.gradle creates the following warning in Google Play Console:

<img width="451" alt="Screen Shot 2020-05-13 at 12 26 37 PM" src="https://user-images.githubusercontent.com/13735532/81850441-34265280-9515-11ea-86bb-c08d05c101d5.png">

It's trivial to extract the API key from the APK. Why not define it in a build config variable instead? Something like:

    // SECRET is defined in a Gradle properties file, excluded from SCM
    variant.buildConfigField "String", "GCP_API_KEY", "\"$SECRET\""

It's still relatively easy to get a hold of this with something like apktool, but I think it's a small improvement.

Adding the API key to the manifest exposes it in a similar way with no easy workaround.

**Comment by arriolac** [comment]
I am also not a fan of the way Maps SDK is currently initialized :( Unfortunately, I don't believe there is a workaround with the warning that you shared w/o changing the initialization behavior on the SDK itself. This has also been pointed out here: https://github.com/googlemaps/android-places-demos/issues/29

Agreed that using a combination of `BuildConfig` + programmatic initialization is more secure and will also solve this warning.

**Comment by dave-kennedy** [comment]
AFAIK no progress has been made on this issue.

**Comment by arriolac** [comment]
Please see my comments (https://github.com/googlemaps/android-places-demos/issues/29#issuecomment-652075747 and https://github.com/googlemaps/android-places-demos/issues/29#issuecomment-655730375) on the latest update on this issue. To summarize, the warning can be safely ignored assuming the proper restrictions have been imposed on the API key. The copy of the warning on the Play Console was also updated to reflect this.

I'd like to keep this feature request open though because it would be good to remove the API key from string resource and the manifest file since those values are easy to obtain.
